- hosts: all
  user: vagrant
  become: yes
  vars:
    config_path: '/vagrant'
  tasks:
    - name: Set system's hostname.
      hostname:
        name: lb.example.local
        
    - name: enable ipv4 routing
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: install keepalived
      yum: name=keepalived state=latest

    - name: install ipvsadm
      yum: name=ipvsadm state=latest

    - name: Copying configuration file for network interface.
      template:
        src: "{{ config_path }}/network/ifcfg-enp0s8.j2"
        dest: /etc/sysconfig/network-scripts/ifcfg-enp0s8

    - name: Modify to default network interface.
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
        regexp: 'DEFROUTE="yes"'
        line: 'DEFROUTE="no"'
